services:
  mysql:
    image: mysql:latest
    container_name: e-commerce-mysql
    restart: always
    ports:
      - "3307:3306"  # Change 3306 to 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystore
